class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.18.tar.gz"
  sha256 "32daa0f5e5e205c631751780ada355cb0e7c5fcdf8d8b7e76739f011928ed059"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "8d691f06a62cb71165d7f50706a3c147ce49070828c7c5fdefac37de4324df89"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "8d691f06a62cb71165d7f50706a3c147ce49070828c7c5fdefac37de4324df89"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "8d691f06a62cb71165d7f50706a3c147ce49070828c7c5fdefac37de4324df89"
    sha256 cellar: :any_skip_relocation, sonoma:        "75ca0bf3df990436fc6dc34ef3b3e8a4dae9a15a10274dfb42de0af2469ce900"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "b22343215e26771ead1a4f41b0c14b10727a094be7b3939104a31a7afcbbd229"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "6c9cabc06a86c9af94981ca3fa0f8f3d25e97969dba0f57130c419a92507dea1"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
