class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.47.tar.gz"
  sha256 "24b56b68e7f0d0760ceea5447ede774327d0b4a6e3e307425a2fc0495602f873"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "499e623e3de03f89ee42502c8e73c9783af3e143947934e78484fd0353f3c0cc"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "499e623e3de03f89ee42502c8e73c9783af3e143947934e78484fd0353f3c0cc"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "499e623e3de03f89ee42502c8e73c9783af3e143947934e78484fd0353f3c0cc"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "92474b4e934ca7e76917f41d8a630f2cb572f7e344e0eaa6f1a1e16f2618120a"
    sha256 cellar: :any,                 x86_64_linux:  "fd150eb9a93f53867b443a6df8b2b334870e49136a38a0de28d70431984eb58c"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
