class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.13.tar.gz"
  sha256 "4d3a0f1df8a505bebf230b3dd13fd4a12a4f3dfc2d1500e7390db9f8ad496554"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "2595aaea8619eef4ab8116a5c57d4c44f9dd836a86d1a57bad34f9a6b75d93df"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "2595aaea8619eef4ab8116a5c57d4c44f9dd836a86d1a57bad34f9a6b75d93df"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "2595aaea8619eef4ab8116a5c57d4c44f9dd836a86d1a57bad34f9a6b75d93df"
    sha256 cellar: :any_skip_relocation, sonoma:        "2eead03f0e2381faa871e9d619422804fb2a92196d96d18fe4b7f1b984e35667"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "a1f5415b66a1d992d80f9ede2415390b8a2ce360dc33418eb4dd7c9f2f710450"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "9af99f156752e9d2e1d77e303bd55958a1750befb7700027ff98b87ba83ed3ed"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
