class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.10.2.tar.gz"
  sha256 "e2568df6596c743f583f65e764e60709d974494c2a12a2b3f1e67ec28a6448d3"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "f97f85c39083b16682f78429fc2a515e62ac206d07ac115b4633783086783960"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "4e2c2372a98ddae575b453d794d60be52298076c4bb120448e6f1b1319258610"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "bc32647b2ab30a77230f7f7b2b9c65f9ec6aaab25391712e0e5c6e7a49d41223"
    sha256 cellar: :any_skip_relocation, sonoma:        "a6dc40773f4965f8bd6c086401bbe0fae43aa66a933d13a24d8fb5fab5c1e297"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "98a4d99a1ae12ceb3cb9ac8d4698f121f406e233d65c864bf07cfbcb49b02c0a"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "fafaf2e2dd4d26c1f47c8c7afe3e172bb519e45bc9a0cacc42e6c466f7f0abf9"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
